In [1]:
!pip install rdkit
!pip install pyg-lib torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.13.0+cu117.html

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.4/29.4 MB 27.5 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://data.pyg.org/whl/torch-1.13.0+cu117.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 43.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 59.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 44.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 51.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 877.7/877.7 KB 40.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 565.0/565.0 KB 19.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.2/280.2 KB 24.5 MB/s eta 0:00:00
  Created wheel for torch-geometric: filename=torch_

In [2]:
import numpy as np
import pandas as pd
import rdkit.Chem as Chem
from sklearn.ensemble import RandomForestClassifier
import sklearn.metrics as metrics
import torch 
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
from torch_geometric.data import Data
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
import seaborn as sns
from torch_geometric.loader import DataLoader
import torch_geometric
from torch_geometric.nn import GCNConv
import os
from sklearn.preprocessing import LabelEncoder
from tqdm import tqdm

In [3]:
!mkdir data
!mkdir /content/data/raw
!mkdir /content/data/processed

In [4]:
!cp "/content/drive/MyDrive/Colab Notebooks/Job_test/cmpd.csv" "/content/data/raw"

In [6]:
cmpd_df = pd.read_csv('/content/data/raw/cmpd.csv')
cmpd_df.head()

inchikey  \
0  FNHKPVJBJVTLMP-UHFFFAOYSA-N   
1  CUDVHEFYRIWYQD-UHFFFAOYSA-N   
2  TTZSNFLLYPYKIL-UHFFFAOYSA-N   
3  UOVCGJXDGOGOCZ-UHFFFAOYSA-N   
4  CUIHSIWYWATEQL-UHFFFAOYSA-N   

                                              smiles  group activity  
0  CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)...  train   active  
1  CNC(=O)c1cccc2cc(Oc3ccnc4cc(OCC5(N)CC5)c(OC)cc...  train   active  
2  Cc1cc2cc(Oc3ccnc(Nc4cccc(CS(=O)(=O)NCCN(C)C)c4...   test   active  
3       COc1cc2c(cc1F)C(c1ccccc1Cl)=Nc1c(n[nH]c1C)N2  train   active  
4  Cc1ccc(Nc2nccc(N(C)c3ccc4c(C)n(C)nc4c3)n2)cc1S...   test   active

In [7]:
train_df = cmpd_df[cmpd_df['group'] == "train"] 
test_df = cmpd_df[cmpd_df['group'] == "test"] 
train_df.reset_index(inplace = True,drop = True)
test_df.reset_index(inplace = True,drop = True)

le=LabelEncoder()
train_df["activity"]=le.fit_transform(train_df["activity"])
test_df["activity"]=le.fit_transform(test_df["activity"])

train_df["activity"] = train_df["activity"].astype(int)
test_df["activity"] = test_df["activity"].astype(int)

train_df.to_csv("/content/data/raw/train.csv")
test_df.to_csv("/content/data/raw/test.csv")

<ipython-input-7-ac65f67fca99>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df["activity"]=le.fit_transform(train_df["activity"])
<ipython-input-7-ac65f67fca99>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df["activity"]=le.fit_transform(test_df["activity"])
<ipython-input-7-ac65f67fca99>:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pand

In [8]:
# label = np.asarray([train_df["activity"]])


In [9]:
# Count each class data points
train_df["activity"].value_counts()

0    2146
1    1075
3     486
2     270
Name: activity, dtype: int64

In [10]:
import torch
from torch_geometric.data import Dataset, download_url


class MoleculeDataset(Dataset):
    def __init__(self, root, filename, transform=None, test=False, pre_transform=None, pre_filter=None):
        """
        root = Where the dataset should be stored. This folder is split
        into raw_dir (downloaded dataset) and processed_dir (processed data). 
        """
        self.test = test
        self.filename = filename
        super(MoleculeDataset, self).__init__(root, transform, pre_transform, pre_filter)

    @property
    def raw_file_names(self):
        """ If this file exists in raw_dir, the download is not triggered.
            (The download func. is not implemented here)  
        """
        return self.filename

    @property
    def processed_file_names(self):
        """ If these files are found in raw_dir, processing is skipped"""
        self.data = pd.read_csv(self.raw_paths[0]).reset_index()

        if self.test:
            return [f'data_test_{i}.pt' for i in list(self.data.index)]
        else:
            return [f'data_{i}.pt' for i in list(self.data.index)]

    def download(self):
        # Download to `self.raw_dir`.
        pass

    def process(self):
        self.data = pd.read_csv(self.raw_paths[0])
        for index, mol in tqdm(self.data.iterrows(), total=self.data.shape[0]):
            mol_obj = Chem.MolFromSmiles(mol["smiles"])
            # Get node features
            node_feats = self._get_node_features(mol_obj)
            # Get edge features
            edge_feats = self._get_edge_features(mol_obj)
            # Get adjacency info
            edge_index = self._get_adjacency_info(mol_obj)
            # Get labels info
            label = self._get_labels(mol["activity"])

            # Create data object
            data = Data(x=node_feats, 
                        edge_index=edge_index,
                        edge_attr=edge_feats,
                        y=label,
                        smiles=mol["smiles"]
                        ) 
            if self.test:
                torch.save(data, 
                    os.path.join(self.processed_dir, 
                                 f'data_test_{index}.pt'))
            else:
                torch.save(data, 
                    os.path.join(self.processed_dir, 
                                 f'data_{index}.pt'))

    def _get_node_features(self, mol):
        """ 
        This will return a matrix / 2d array of the shape
        [Number of Nodes, Node Feature size]
        """
        all_node_feats = []

        for atom in mol.GetAtoms():
            node_feats = []
            # Feature 1: Atomic number        
            node_feats.append(atom.GetAtomicNum())
            # Feature 2: Atom degree
            node_feats.append(atom.GetDegree())
            # Feature 3: Formal charge
            node_feats.append(atom.GetFormalCharge())
            # Feature 4: Hybridization
            node_feats.append(atom.GetHybridization())
            # Feature 5: Aromaticity
            node_feats.append(atom.GetIsAromatic())
            # Feature 6: Total Num Hs
            node_feats.append(atom.GetTotalNumHs())
            # Feature 7: Radical Electrons
            node_feats.append(atom.GetNumRadicalElectrons())
            # Feature 8: In Ring
            node_feats.append(atom.IsInRing())
            # Feature 9: Chirality
            node_feats.append(atom.GetChiralTag())

            # Append node features to matrix
            all_node_feats.append(node_feats)

        all_node_feats = np.asarray(all_node_feats)
        return torch.tensor(all_node_feats, dtype=torch.float)

    def _get_edge_features(self, mol):
        """ 
        This will return a matrix / 2d array of the shape
        [Number of edges, Edge Feature size]
        """
        all_edge_feats = []

        for bond in mol.GetBonds():
            edge_feats = []
            # Feature 1: Bond type (as double)
            edge_feats.append(bond.GetBondTypeAsDouble())
            # Feature 2: Rings
            edge_feats.append(bond.IsInRing())
            # Append node features to matrix (twice, per direction)
            all_edge_feats += [edge_feats, edge_feats]

        all_edge_feats = np.asarray(all_edge_feats)
        return torch.tensor(all_edge_feats, dtype=torch.float)

    def _get_adjacency_info(self, mol):
        """
        We could also use rdmolops.GetAdjacencyMatrix(mol)
        but we want to be sure that the order of the indices
        matches the order of the edge features
        """
        edge_indices = []
        for bond in mol.GetBonds():
            i = bond.GetBeginAtomIdx()
            j = bond.GetEndAtomIdx()
            edge_indices += [[i, j], [j, i]]

        edge_indices = torch.tensor(edge_indices)
        edge_indices = edge_indices.t().to(torch.long).view(2, -1)
        return edge_indices

    def _get_labels(self, label):
        label = np.asarray([label])
        label = label.astype(np.int64)
        return torch.tensor(label, dtype=torch.int64)

    def len(self):
        return self.data.shape[0]

    def get(self, idx):
        """ - Equivalent to __getitem__ in pytorch
            - Is not needed for PyG's InMemoryDataset
        """
        if self.test:
            data = torch.load(os.path.join(self.processed_dir, 
                                 f'data_test_{idx}.pt'))
        else:
            data = torch.load(os.path.join(self.processed_dir, 
                                 f'data_{idx}.pt'))        
        return data

In [12]:
# dataset = MoleculeDataset(root = "/content/data/")

In [15]:
# print(dataset[0].edge_index.t())
# print(dataset[0].x)
# print(dataset[0].edge_attr)
# print(dataset[0].y)


# **GNN Architecture**

In [20]:
import torch
import torch.nn.functional as F 
from torch.nn import Linear, BatchNorm1d, ModuleList
from torch_geometric.nn import TransformerConv, TopKPooling 
from torch_geometric.nn import GATConv
from torch_geometric.nn import global_mean_pool as gap, global_max_pool as gmp
from sklearn.metrics import confusion_matrix, f1_score, \
    accuracy_score, precision_score, recall_score, roc_auc_score
import numpy as np
from tqdm import tqdm
torch.manual_seed(42)

In [37]:
class GNN(torch.nn.Module):
    def __init__(self, feature_size):
        super(GNN, self).__init__()
        num_classes = 4
        embedding_size = 1024

        # GNN layer
        self.conv1 = GATConv(feature_size, embedding_size, heads=3, dropout=0.3)
        self.head_transform1 = Linear(embedding_size * 3, embedding_size)
        self.pool1 = TopKPooling(embedding_size, ratio = 0.8)
        self.conv2 = GATConv(embedding_size, embedding_size, heads=3, dropout=0.3)
        self.head_transform2 = Linear(embedding_size*3, embedding_size)
        self.pool2 = TopKPooling(embedding_size, ratio=0.5)
        self.conv3 = GATConv(embedding_size, embedding_size, heads=3, dropout=0.3)
        self.head_transform3 = Linear(embedding_size*3, embedding_size)
        self.pool3 = TopKPooling(embedding_size, ratio=0.2)

        # Linear layers
        self.linear1 = Linear(embedding_size*2, 1024)
        self.linear2 = Linear(1024, num_classes)

    def forward(self, x, edge_attr, edge_index, batch_index):
        # First block
        x = self.conv1(x, edge_index)
        x = self.head_transform1(x)

        x, edge_index, edge_attr, batch_index, _, _ = self.pool1(x, edge_index,
                                                                 None, batch_index)
        x1 = torch.cat([gmp(x, batch_index), gap(x, batch_index)], dim=1)

        #second block
        x = self.conv2(x, edge_index)
        x = self.head_transform2(x)
        x, edge_index, edge_attr, batch_index, _, _ = self.pool2(x, edge_index, None, batch_index)
        x2 = torch.cat([gmp(x, batch_index), gap(x, batch_index)], dim=1)

        # third block
        x = self.conv3(x, edge_index)
        x = self.head_transform3(x)
        x, edge_index, edge_attr, batch_index, _, _ = self.pool3(x, edge_index, None, batch_index)
        x3 = torch.cat([gmp(x, batch_index), gap(x, batch_index)], dim=1)

        # Concat pooled vectors
        x = x1 + x2 + x3

        # output block
        x = self.linear1(x).relu()
        x = F.dropout(x, p=0.5, training = self.training)
        x = self.linear2(x)

        return x


# **Training the data**

In [38]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [18]:
train_dataset = MoleculeDataset(root="/content/data/", filename="train.csv")
test_dataset = MoleculeDataset(root="/content/data/", filename="test.csv")

Processing...
100%|██████████| 3977/3977 [00:14<00:00, 279.48it/s]
Done!


In [39]:
def count_parameters(model):  
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

In [48]:
# Loading the model

model = GNN(feature_size=train_dataset[0].x.shape[1])
model = model.to(device)
print(f"Number of parameters: {count_parameters(model)}")
model

Number of parameters: 17892356


GNN(
  (conv1): GATConv(9, 1024, heads=3)
  (head_transform1): Linear(in_features=3072, out_features=1024, bias=True)
  (pool1): TopKPooling(1024, ratio=0.8, multiplier=1.0)
  (conv2): GATConv(1024, 1024, heads=3)
  (head_transform2): Linear(in_features=3072, out_features=1024, bias=True)
  (pool2): TopKPooling(1024, ratio=0.5, multiplier=1.0)
  (conv3): GATConv(1024, 1024, heads=3)
  (head_transform3): Linear(in_features=3072, out_features=1024, bias=True)
  (pool3): TopKPooling(1024, ratio=0.2, multiplier=1.0)
  (linear1): Linear(in_features=2048, out_features=1024, bias=True)
  (linear2): Linear(in_features=1024, out_features=4, bias=True)
)

In [49]:
# Loss and Optimizer 
# weights = torch.tensor([1,10], dtype=torch.float32).to(device)
# loss_fn = torch.nn.CrossEntropyLoss(weight=weights)
loss_fn = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.95)

In [50]:
# NUM_GRAPHS_PER_BATCH = 256
NUM_GRAPHS_PER_BATCH = 64
train_loader = DataLoader(train_dataset, batch_size=NUM_GRAPHS_PER_BATCH, shuffle = True)
test_loader = DataLoader(test_dataset, batch_size=NUM_GRAPHS_PER_BATCH, shuffle = True)

In [57]:
def train(epoch):
  # Enumerate over the data
    all_preds = []
    all_labels = []
    running_loss = 0.0
    # step = 0
    for _, batch in enumerate(tqdm(train_loader)):
        # Use GPU
        batch.to(device)  
        # Reset gradients
        optimizer.zero_grad() 
        # Passing the node features and the connection info
        pred = model(batch.x.float(), 
                                batch.edge_attr.float(),
                                batch.edge_index, 
                                batch.batch) 
        # Calculating the loss and gradients
        loss = torch.sqrt(loss_fn(pred, batch.y))
        loss.backward()  
        optimizer.step()  
        # Update tracking
        running_loss += loss.item()
        # step += 1
        all_preds.append(np.argmax(pred.cpu().detach().numpy(), axis=1))
        all_labels.append(batch.y.cpu().detach().numpy())
    all_preds = np.concatenate(all_preds).ravel()
    all_labels = np.concatenate(all_labels).ravel()
    calculate_metrics(all_preds, all_labels, epoch, "train")
    return loss

In [55]:
def test(epoch):
    all_preds = []
    all_labels = []
    running_loss = 0.0
    step = 0
    for batch in test_loader:
        batch.to(device)  
        pred = model(batch.x.float(), 
                        batch.edge_attr.float(),
                        batch.edge_index, 
                        batch.batch) 
        loss = torch.sqrt(loss_fn(pred, batch.y))
        all_preds.append(np.argmax(pred.cpu().detach().numpy(), axis = 1))
        all_labels.append(batch.y.cpu().detach().numpy())
    
    all_preds = np.concatenate(all_preds).ravel()
    all_labels = np.concatenate(all_labels).ravel()
    calculate_metrics(all_preds, all_labels, epoch, "test")
    return loss

In [56]:
def calculate_metrics(y_pred, y_true, epoch, type):
    print(f"\n Confusion matrix: \n {confusion_matrix(y_pred, y_true)}")
    print(f"F1 Score: {f1_score(y_true, y_pred, average='macro')}")
    print(f"Accuracy: {accuracy_score(y_true, y_pred)}")
    prec = precision_score(y_true, y_pred, average='macro')
    rec = recall_score(y_true, y_pred, average='macro')
    print(f"Precision: {prec}")
    print(f"Recall: {rec}")
    # mlflow.log_metric(key=f"Precision-{type}", value=float(prec), step=epoch)
    # mlflow.log_metric(key=f"Recall-{type}", value=float(rec), step=epoch)
    try:
        roc = roc_auc_score(y_true, y_pred)
        print(f"ROC AUC: {roc}")
        # mlflow.log_metric(key=f"ROC-AUC-{type}", value=float(roc), step=epoch)
    except:
        # mlflow.log_metric(key=f"ROC-AUC-{type}", value=float(0), step=epoch)
        print(f"ROC AUC: notdefined")

In [ ]:
for epoch in range(300): 
    # Training
    model.train()
    loss = train(epoch=epoch)
    loss = loss.detach().cpu().numpy()
    print(f"Epoch {epoch} | Train Loss {loss}")

    # Testing
    model.eval()
    if epoch % 5 == 0:
        loss = test(epoch = epoch)
        loss = loss.detach().cpu().numpy()
        print(f"Epochs {epoch} | test Loss {loss}")

    scheduler.step()
print("Done!")
    # mlflow.log_metric(key="Train loss", value=float(loss), step=epoch)

    # Testing
    # model.eval()
    # if epoch % 5 == 0:
    #         loss = test(epoch, model, test_loader, loss_fn)
    #         print(f"Epoch {epoch} | Test Loss {loss}")
    #         mlflow.log_metric(key="Test loss", value=float(loss), step=epoch)
            
    #         # Update best loss
    #         if float(loss) < best_loss:
    #             best_loss = loss
    #             # Save the currently best model 
    #             mlflow.pytorch.log_model(model, "model", signature=SIGNATURE)
    #             early_stopping_counter = 0
    #         else:
    #             early_stopping_counter += 1

    #     scheduler.step()
    # else:
    #     print("Early stopping due to no improvement.")
    #     return [best_loss]
    # print(f"Finishing training with best test loss: {best_loss}")
    # return [best_loss]

100%|██████████| 63/63 [03:45<00:00,  3.58s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[2142 1068  269  484]
 [   4    7    1    2]
 [   0    0    0    0]
 [   0    0    0    0]]
F1 Score: 0.17852906661519885
Accuracy: 0.5403570530550666
Precision: 0.2601249053747161
Recall: 0.25116192375214025
ROC AUC: notdefined
Epoch 0 | Train Loss 1.0346851348876953


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[578 658 109 208]
 [  0   0   0   0]
 [  0   0   0   0]
 [  0   0   0   0]]
F1 Score: 0.1356170811825434
Accuracy: 0.37218287186091437
Precision: 0.09304571796522859
Recall: 0.25
ROC AUC: notdefined
Epochs 0 | test Loss 1.1075352430343628


100%|██████████| 63/63 [03:41<00:00,  3.52s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[2129 1057  264  485]
 [  17   18    6    1]
 [   0    0    0    0]
 [   0    0    0    0]]
F1 Score: 0.18311074148650044
Accuracy: 0.5398541614282122
Precision: 0.24240333998910873
Recall: 0.2522056178070613
ROC AUC: notdefined
Epoch 1 | Train Loss 0.9960204362869263


100%|██████████| 63/63 [03:42<00:00,  3.53s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[2102 1019  263  473]
 [  44   56    7   13]
 [   0    0    0    0]
 [   0    0    0    0]]
F1 Score: 0.19851008944621135
Accuracy: 0.5426200653759115
Precision: 0.25291245354766223
Recall: 0.2578974403433104
ROC AUC: notdefined
Epoch 2 | Train Loss 1.0955463647842407


100%|██████████| 63/63 [03:42<00:00,  3.53s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[2020  904  246  434]
 [ 126  171   24   52]
 [   0    0    0    0]
 [   0    0    0    0]]
F1 Score: 0.2346991352390103
Accuracy: 0.5509177772190093
Precision: 0.2547333466240965
Recall: 0.2750889702854418
ROC AUC: notdefined
Epoch 3 | Train Loss 1.0364735126495361


100%|██████████| 63/63 [03:41<00:00,  3.52s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1968  899  231  411]
 [ 178  176   39   75]
 [   0    0    0    0]
 [   0    0    0    0]]
F1 Score: 0.23103706135864716
Accuracy: 0.5390998239879305
Precision: 0.23422798030948502
Recall: 0.27019397906326537
ROC AUC: notdefined
Epoch 4 | Train Loss 1.134735107421875


100%|██████████| 63/63 [03:40<00:00,  3.50s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[2090 1006  260  467]
 [  54   69   10   18]
 [   0    0    0    0]
 [   2    0    0    1]]
F1 Score: 0.2042339897316044
Accuracy: 0.5431229570027659
Precision: 0.33424451400521643
Recall: 0.26003714977563325
ROC AUC: notdefined
Epoch 5 | Train Loss 1.1651785373687744


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[555 609 103 206]
 [ 23  49   6   2]
 [  0   0   0   0]
 [  0   0   0   0]]
F1 Score: 0.16849768570820764
Accuracy: 0.38892466194462333
Precision: 0.24732051934826885
Recall: 0.2586689243907826
ROC AUC: notdefined
Epochs 5 | test Loss 0.9306691288948059


100%|██████████| 63/63 [03:44<00:00,  3.56s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1913  808  231  403]
 [ 226  267   39   78]
 [   0    0    0    0]
 [   7    0    0    5]]
F1 Score: 0.25812604379056536
Accuracy: 0.5494091023384461
Precision: 0.3561413313462494
Recall: 0.2875215168835413
ROC AUC: notdefined
Epoch 6 | Train Loss 0.7994335889816284


100%|██████████| 63/63 [03:41<00:00,  3.52s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1967  850  246  410]
 [ 173  224   23   67]
 [   0    0    0    0]
 [   6    1    1    9]]
F1 Score: 0.2556804113417076
Accuracy: 0.5531807895398542
Precision: 0.3889349575645532
Recall: 0.28586990358441844
ROC AUC: notdefined
Epoch 7 | Train Loss 1.0706307888031006


100%|██████████| 63/63 [03:43<00:00,  3.55s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1868  763  221  360]
 [ 269  311   47  109]
 [   0    0    0    0]
 [   9    1    2   17]]
F1 Score: 0.2766877934771029
Accuracy: 0.5521750062861454
Precision: 0.3975825900483756
Recall: 0.298684603252455
ROC AUC: notdefined
Epoch 8 | Train Loss 0.8935868740081787


100%|██████████| 63/63 [03:40<00:00,  3.50s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1872  770  221  384]
 [ 256  302   44   91]
 [   0    0    0    0]
 [  18    3    5   11]]
F1 Score: 0.269481808545053
Accuracy: 0.5494091023384461
Precision: 0.32740397915944575
Recall: 0.2939711434681585
ROC AUC: notdefined
Epoch 9 | Train Loss 1.0829771757125854


100%|██████████| 63/63 [03:42<00:00,  3.53s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1831  710  201  348]
 [ 306  364   68  127]
 [   0    0    0    0]
 [   9    1    1   11]]
F1 Score: 0.27948841625515153
Accuracy: 0.5546894644204174
Precision: 0.3783414707147801
Recall: 0.3036134200671312
ROC AUC: notdefined
Epoch 10 | Train Loss 1.0229884386062622


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[  0   0   0   0]
 [569 658 103 156]
 [  0   0   0   0]
 [  9   0   6  52]]
F1 Score: 0.24799694708276798
Accuracy: 0.45717965228589824
Precision: 0.30472971615676664
Recall: 0.3125
ROC AUC: notdefined
Epochs 10 | test Loss 1.1210947036743164


100%|██████████| 63/63 [03:43<00:00,  3.55s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1850  719  213  353]
 [ 288  355   54  117]
 [   0    0    0    0]
 [   8    1    3   16]]
F1 Score: 0.2846854836262028
Accuracy: 0.5584611516218255
Precision: 0.39941453757243234
Recall: 0.3063058335890912
ROC AUC: notdefined
Epoch 11 | Train Loss 0.953877866268158


100%|██████████| 63/63 [03:42<00:00,  3.53s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1850  728  206  360]
 [ 286  347   62  109]
 [   0    0    0    0]
 [  10    0    2   17]]
F1 Score: 0.28369942655318725
Accuracy: 0.5567010309278351
Precision: 0.40155533205255634
Recall: 0.30495977176499317
ROC AUC: notdefined
Epoch 12 | Train Loss 0.9270471334457397


100%|██████████| 63/63 [03:41<00:00,  3.52s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1760  655  193  336]
 [ 378  416   74  126]
 [   0    0    0    0]
 [   8    4    3   24]]
F1 Score: 0.2962768163799384
Accuracy: 0.5531807895398542
Precision: 0.4079304421848819
Recall: 0.3141224838845796
ROC AUC: notdefined
Epoch 13 | Train Loss 0.8559929132461548


100%|██████████| 63/63 [03:40<00:00,  3.49s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1825  713  203  354]
 [ 308  360   62  107]
 [   0    0    0    0]
 [  13    2    5   25]]
F1 Score: 0.2917907437139186
Accuracy: 0.5556952476741263
Precision: 0.3938309563928408
Recall: 0.3091858587626207
ROC AUC: notdefined
Epoch 14 | Train Loss 0.857697606086731


100%|██████████| 63/63 [03:41<00:00,  3.52s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1802  680  201  322]
 [ 328  393   67  138]
 [   0    0    0    0]
 [  16    2    2   26]]
F1 Score: 0.29755448152496367
Accuracy: 0.5584611516218255
Precision: 0.3973226650295958
Recall: 0.3146952771179805
ROC AUC: notdefined
Epoch 15 | Train Loss 1.1635258197784424


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[  0   0   0   0]
 [569 658 103 156]
 [  0   0   0   0]
 [  9   0   6  52]]
F1 Score: 0.24799694708276798
Accuracy: 0.45717965228589824
Precision: 0.30472971615676664
Recall: 0.3125
ROC AUC: notdefined
Epochs 15 | test Loss 1.1292816400527954


100%|██████████| 63/63 [03:41<00:00,  3.52s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1839  696  211  335]
 [ 291  376   56  121]
 [   0    0    0    0]
 [  16    3    3   30]]
F1 Score: 0.3017622583212776
Accuracy: 0.5644958511440784
Precision: 0.40482620894613214
Recall: 0.31710974674219794
ROC AUC: notdefined
Epoch 16 | Train Loss 0.926084578037262


100%|██████████| 63/63 [03:43<00:00,  3.55s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1812  727  193  337]
 [ 322  346   70  119]
 [   0    0    0    0]
 [  12    2    7   30]]
F1 Score: 0.2912071004300311
Accuracy: 0.5501634397787277
Precision: 0.39559739553318496
Recall: 0.30698761579007505
ROC AUC: notdefined
Epoch 17 | Train Loss 1.0514963865280151


100%|██████████| 63/63 [03:39<00:00,  3.48s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1799  631  186  310]
 [ 333  435   79  147]
 [   0    0    0    0]
 [  14    9    5   29]]
F1 Score: 0.30917296153609825
Accuracy: 0.5690218757857681
Precision: 0.390307555059223
Recall: 0.3256564414365359
ROC AUC: notdefined
Epoch 18 | Train Loss 1.039917230606079


100%|██████████| 63/63 [03:44<00:00,  3.56s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1794  648  182  345]
 [ 338  426   87  121]
 [   0    0    0    0]
 [  14    1    1   20]]
F1 Score: 0.29857837125348713
Accuracy: 0.5632386220769424
Precision: 0.3995177534107589
Recall: 0.3183513095203374
ROC AUC: notdefined
Epoch 19 | Train Loss 1.0728449821472168


100%|██████████| 63/63 [03:42<00:00,  3.53s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1776  619  175  302]
 [ 363  456   88  161]
 [   0    0    0    0]
 [   7    0    7   23]]
F1 Score: 0.30534436830380685
Accuracy: 0.5670103092783505
Precision: 0.4167430787176648
Recall: 0.32477433907220954
ROC AUC: notdefined
Epoch 20 | Train Loss 1.0812360048294067


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[  2   0   0   0]
 [567 658 104 156]
 [  0   0   0   0]
 [  9   0   5  52]]
F1 Score: 0.25013774734004224
Accuracy: 0.4584674822923374
Precision: 0.5577441077441077
Recall: 0.3133650519031142
ROC AUC: notdefined
Epochs 20 | test Loss 1.1816281080245972


100%|██████████| 63/63 [03:39<00:00,  3.49s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1761  568  172  291]
 [ 365  500   91  161]
 [   0    0    0    0]
 [  20    7    7   34]]
F1 Score: 0.3230480725762692
Accuracy: 0.5770681418154388
Precision: 0.39458955822108444
Recall: 0.33891789633347147
ROC AUC: notdefined
Epoch 21 | Train Loss 1.0155065059661865


100%|██████████| 63/63 [03:43<00:00,  3.54s/it]



 Confusion matrix: 
 [[1793  579  172  291]
 [ 336  484   89  158]
 [   1    1    0    0]
 [  16   11    9   37]]
F1 Score: 0.3260572758758889
Accuracy: 0.5818456122705556
Precision: 0.39822726540233483
Recall: 0.3404680417742879
ROC AUC: notdefined
Epoch 22 | Train Loss 1.0518993139266968


100%|██████████| 63/63 [03:40<00:00,  3.50s/it]



 Confusion matrix: 
 [[1788  605  174  278]
 [ 335  463   87  167]
 [   1    0    0    0]
 [  22    7    9   41]]
F1 Score: 0.3242443462067528
Accuracy: 0.5763138043751571
Precision: 0.39689310299267144
Recall: 0.33705945498202466
ROC AUC: notdefined
Epoch 23 | Train Loss 1.0333137512207031


100%|██████████| 63/63 [03:42<00:00,  3.53s/it]



 Confusion matrix: 
 [[1759  537  171  272]
 [ 377  532   92  174]
 [   1    1    0    0]
 [   9    5    7   40]]
F1 Score: 0.3348262351783484
Accuracy: 0.5861201910988182
Precision: 0.4376772116846751
Recall: 0.34921318493937226
ROC AUC: notdefined
Epoch 24 | Train Loss 0.9733000993728638


100%|██████████| 63/63 [03:41<00:00,  3.52s/it]
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[1733  537  166  273]
 [ 401  533   98  177]
 [   0    0    0    0]
 [  12    5    6   36]]
F1 Score: 0.3281845820277301
Accuracy: 0.5788282625094292
Precision: 0.4226872900630323
Recall: 0.34435923895025733
ROC AUC: notdefined
Epoch 25 | Train Loss 0.9668428301811218


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 Confusion matrix: 
 [[  0   0   0   0]
 [569 658 103 156]
 [  0   0   0   0]
 [  9   0   6  52]]
F1 Score: 0.24799694708276798
Accuracy: 0.45717965228589824
Precision: 0.30472971615676664
Recall: 0.3125
ROC AUC: notdefined
Epochs 25 | test Loss 1.130495309829712


100%|██████████| 63/63 [03:45<00:00,  3.58s/it]



 Confusion matrix: 
 [[1726  513  159  260]
 [ 398  548  101  176]
 [   3    0    0    1]
 [  19   14   10   49]]
F1 Score: 0.3412636249048881
Accuracy: 0.5841086245914006
Precision: 0.4075119031311216
Recall: 0.3537193831985777
ROC AUC: notdefined
Epoch 26 | Train Loss 0.9087729454040527


100%|██████████| 63/63 [03:41<00:00,  3.52s/it]



 Confusion matrix: 
 [[1759  564  165  299]
 [ 365  504  101  148]
 [   0    0    0    1]
 [  22    7    4   38]]
F1 Score: 0.327311464889867
Accuracy: 0.578576816696002
Precision: 0.40429021911960394
Recall: 0.34167275044803336
ROC AUC: notdefined
Epoch 27 | Train Loss 1.069650650024414


 54%|█████▍    | 34/63 [02:03<01:38,  3.39s/it]